# Generated by Django 4.2.5 on 2023-10-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
