# Generated by Django 4.2.5 on 2023-10-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentacar', '0005_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('carName', models.CharField(max_length=255)),
                ('carType', models.CharField(max_length=100)),
                ('carDescription', models.TextField()),
                ('carRate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
