# Generated by Django 4.2.6 on 2023-10-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carPic',
            field=models.ImageField(blank=True, null=True, upload_to='car_pics/'),
        ),
    ]
