# Generated by Django 4.2.6 on 2023-10-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0007_car_carpic'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
