# Generated by Django 4.2.6 on 2023-10-25 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rentacar', '0008_car_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('carName', models.CharField(max_length=255)),
                ('dateRange', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('carid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentacar.car')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
