# Generated by Django 4.2.6 on 2023-10-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateRange',
        ),
        migrations.AddField(
            model_name='order',
            name='endDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='startDate',
            field=models.DateField(default=None),
        ),
    ]
