# Generated by Django 4.2.6 on 2023-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0010_remove_order_daterange_order_enddate_order_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.FloatField(),
        ),
    ]
