# Generated by Django 4.2.5 on 2023-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0012_alter_car_carrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
