# Generated by Django 4.2.7 on 2023-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0014_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed'), (2, 'Canceled'), (3, 'Reserved')], default=0),
        ),
    ]
